-- lua/dodot/types.lua
-- Defines the core data structures for dodot

local M = {}

--- Represents a discovered dotfile pack.
-- @field path string Absolute path to the pack directory.
-- @field name string Name of the pack (typically the directory name).
-- @field config table|nil Pack-specific configuration from .dodot.toml (if any).
M.Pack = {
  path = "",
  name = "",
  config = nil,
}

--- Represents a successful match made by a Trigger via a Matcher configuration.
-- This is what's passed to the PowerUp processing stage.
-- @field trigger_name string The name/type of the trigger that fired (e.g., "FileNameTrigger").
-- @field file_path string The path of the file within the pack that the trigger matched.
-- @field pack_path string The path to the pack containing the matched file.
-- @field metadata table|nil Optional metadata provided by the trigger's match function.
-- @field power_up_name string The name of the power-up to be invoked for this match.
-- @field priority number The priority of the matcher configuration that led to this match.
-- @field options table|nil Options to be passed to the power-up's process function.
M.TriggerMatch = {
  trigger_name = "",
  file_path = "",
  pack_path = "",
  metadata = nil,
  power_up_name = "",
  priority = 0,
  options = nil,
}

--- Represents a high-level action to be performed, generated by a PowerUp.
-- @field type string The type of action (e.g., "symlink", "shell_source", "brew_install").
-- @field description string A human-readable description of the action.
-- @field data table Action-specific data required to execute the action.
-- @field pack_source string The name of the pack that this action originated from.
-- @field priority number|nil Optional priority for ordering actions if needed.
M.Action = {
  type = "",
  description = "",
  data = {},
  pack_source = "",
  priority = nil,
}

--- Represents a low-level filesystem operation, compatible with fsynth.
-- @field type string The fsynth operation type (e.g., "fsynth.op.symlink", "fsynth.op.create_file").
-- @field description string A human-readable description of the filesystem operation.
-- @field args table A table of arguments for the fsynth operation function.
M.Operation = {
  type = "",
  description = "",
  args = {},
}

-- Basic validation functions (optional for Phase 2.1, but good practice)
-- For now, these can just be placeholders or very simple checks.

function M.is_pack(obj)
  return type(obj) == "table" and type(obj.path) == "string" and type(obj.name) == "string"
end

-- Add similar is_trigger_match, is_action, is_operation functions if desired.

return M
